### ISSUE TITLE
Setting the delete_permission or edit_permission to false makes the actions column disapear

### ISSUE THREAD

**Issue by Ghitu** [tabacitu/dick#20]
The condition for hiding the Actions column is wrong (view/crud/list.blade.php lines 82, 104) it should be something like this  @if ( !( isset($crud['edit_permission']) && $crud['edit_permission'] === false && isset($crud['delete_permission']) && $crud['delete_permission'] === false ) )

**Comment by eugentudorache** [comment]
Hi,

We are planning a small journey this month and I need you to take a look at our route and tell what you think <http://pynduwysti.marshalwallets.co/aeoajvz>

Take care, eugen@updivision.com
