### ISSUE TITLE
Multi-language CRUDs, entities, everything

### ISSUE THREAD

**Issue by tabacitu** [tabacitu/dick#26]
By the end of the week, Dick will support multiple tongues - client's deadline. It's just a website, but let's think future-proof. Say you have an application that needs all db entities translated. Or most of them. Say:
- products
- categories
- pages
- news

The two best solutions I've found are:
1) a new translation table for each entity (so we have products[id, price, timestamps] and product_translations[id, product_id, lang, name, description]);
PROs:
- This seems the closest to the db normal form; I'm sure my university professors will bow to me and congratulate their young padawan for putting standards over ease of use;
CONs:
- This will mean we need a new table for each entity (so twice the number of tables in the db) and a complete overhaul of how the CRUD works. When a user updates a product (price, name, desc) you need to update some items in the products table, some in the product_translations; it will get very messy very fast;
- This will definitely raise the number of queries in the application and/or query time; two tables are slower than one;

2) store all translations as child products (so we add a few columns to the products table: lang and translation_of);
PROs:
- Faster to implement: since the CRUD will work just as it is now, we only need to add links to edit/delete the corresponding translations);
- Faster to run: this will keep the number of db tables down;
- Faster to upgrade to: this will make it easy to turn a single-language to a multi-language application;
CONs:
- This does mean that the products table won't have a different product on each row; which is... non-standard? Right?

I like solution number two better, but I need someone to tell me I'm sane for thinking that's a really good compromise and normal form is not such a big deal.

 @Ghitu , @eugentudorache , @cristiantone , what do you think? Please reply.

**Comment by noxify** [comment]
Hi,


we had the same problem in our package and we have implement solution number one.

The reason was: For the user it's more comfortable to have only one record, where he/she can modify the record (e.g. Product).

Maybe to extend the migration script should/can/may help.. something like `->translateable()` which is the identifier to create a new field in the translation table (e.g. products_translations) and not in the main table (e.g. products).

**Comment by tabacitu** [comment]
Wow, never thought of extending the migration. That's a great idea, thanks Marcus. That will make it SO much easier to create translatable entities. No matter the solution, ->translatable() will be included :+1: 

In solution 2, the user definitely wouldn't see a product for every translation, he'd see something like
Product name    [en] [fr] [de] [es]
Second product [en] [fr] [de] [es]
just like he would in solution 1. The UX will be the same, only the db admin would see the way they're stored, directly in the db table.

**Comment by noxify** [comment]
```
In solution 2, the user definitely wouldn't see a product for every translation, he'd see something like
Product name [en] [fr] [de] [es]
Second product [en] [fr] [de] [es]
just like he would in solution 1. The UX will be the same, only the db admin would see the way they're stored, directly in the db table.
```

Then I think solution two would be the better option and easier to implement.
Or maybe both solution so everyone can choose the right one for each model/entity?

**Comment by tabacitu** [comment]
Added in https://github.com/tabacitu/dick/commit/d9b69e187ff33a4f645b4e429ecbc3369ae00aa6 using solution 2. 

Specifics on how it looks and works in the docs: https://docs.google.com/document/d/1Dlly560hS1yRrWypNQVedHGlXNP1Jx-W5yPUQ1sQvOQ/edit#heading=h.3sob2ynpkp7c

**Comment by noxify** [comment]
awesome @tabacitu - good work!
