### ISSUE TITLE
ErrorException in FileViewFinder.php line 137:

### ISSUE THREAD

**Issue by SaifulAzam** [tabacitu/dick#27]
Hey i am getting this error when i try to create page from admin

View [fields.select_template] not found. (View: /var/www/site.com/vendor/dick/crud/src/resources/views/form_content.blade.php) (View: /var/www/site.com/vendor/dick/crud/src/resources/views/form_content.blade.php)

**Comment by tabacitu** [comment]
Hi Saiful. Most probably, it's because of the updates I've recently pushed to the CRUD package. Please run a "composer update", that should fix it.

Also, please notice that in recent versions, the CRUD methods store_crud() and update_crud() have been renamed to storeCrud() and updateCrud(). If your ExampleEntityCrudControllers mention those methods, please replace them so you don't have any issues.

**Comment by SaifulAzam** [comment]
yes update and in ExampleEntityCrudControllers everything look new update. but still same error

**Comment by tabacitu** [comment]
That error makes no sense if the update has been successful. Please check your composer.json for the dick version you required. Try: "dick/crud": "^0.7", then "composer update".

If that still doesn't solve it, please check var/www/site.com/vendor/dick/crud/CHANGELOG.md. Is the last mention version [0.7.8] - 2015-09-08?

**Comment by SaifulAzam** [comment]
okay i check it its  "dick/crud": "0.*" then change to  "dick/crud": "^0.7" and composer update 
i got this error
Problem 1
    - dick/crud 0.7 requires zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - dick/crud 0.7.1 requires zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - dick/crud 0.7.2 requires zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - dick/crud 0.7.3 requires zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - dick/crud 0.7.4 requires zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - dick/crud 0.7.5 requires zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - dick/crud 0.7.6 requires zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - dick/crud 0.7.7 requires zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - dick/crud 0.7.8 requires zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].
    - Conclusion: don't install zizaco/entrust dev-master
    - Installation request for dick/crud ^0.7 -> satisfiable by dick/crud[0.7, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8].

**Comment by tabacitu** [comment]
Does your composer.json require any other version of zizaco/entrust than
dev-master? It should require dev-master. Here's what the latest version of
Dick requires: https://github.com/tabacitu/dick/blob/master/composer.json

If it's not too late, I recommend you download the latest version of Dick,
0.6.3. There have been major updates today. One more features will come
tomorrow (multi-language), followed by a period of polishing, no big
updates or new packages.
ᐧ

**Comment by SaifulAzam** [comment]
ok just copy https://github.com/tabacitu/dick/blob/master/composer.json into my composer.json
then composer update
now getting this
file_put_contents(/var/www/site.com/bootstrap/cache/services.json): failed to open stream: Permission denied

**Comment by SaifulAzam** [comment]
Thank you i got it just forgot to run this comment 

php artisan cache:clear 

chmod -R 777 storage 

composer dump-autoload

**Comment by tabacitu** [comment]
Great to hear that!
