### ISSUE TITLE
NotFoundHttpException 

### ISSUE THREAD

**Issue by SaifulAzam** [tabacitu/dick#28]
Hey sorry i am here again with another error

When i click "Browse Uploads" in article, then popup window come and show this error "NotFoundHttpException in Application.php line 879: "

Sorry for disturbing you, i am QA Automation professional Alyse looking debug, bug etc..

**Comment by tabacitu** [comment]
Hi, I think the backup-manager assets are not published. Please check the installation here: https://github.com/tabacitu/backupmanager

**Comment by SaifulAzam** [comment]
Thank you its work

**Comment by SaifulAzam** [comment]
Where is the menu_items and  languages migration?

**Comment by tabacitu** [comment]
ᐧ
It's in the menumanager package: https://github.com/tabacitu/menumanager
Still haven't figured out wether Dick should come with all packages
installed or not.

Run: php artisan migrate
--path=vendor/dick/menumanager/src/database/migrations

**Comment by tabacitu** [comment]
Was everything ok after all? Can I close this issue?

I'll add another issue to go through the installation process once again and write some actual documentation on how to install it.

**Comment by eugentudorache** [comment]
Hello!

 

New message, please read <http://giayhieuchinhhang.com/clear.php?n86r4>

 

eugen@updivision.com

**Comment by eugentudorache** [comment]
Hello!

 

New message, please read <http://dev.velomarket.by/probably.php?djx5>

 

eugen@updivision.com

**Comment by eugentudorache** [comment]
Hello!

 

New message, please read <http://jamesfstadler.com/peaceful.php?xyg>

 

eugen@updivision.com

**Comment by eugentudorache** [comment]
Hello!

 

New message, please read <http://leepak.org/operating.php?0jtu>

 

eugen@updivision.com

**Comment by eugentudorache** [comment]
Hey, Don't miss up this new stuff, you're going to be delighted, read more here <http://ntoshymuce.bloggables.com/aefnfntd?v9f>

eugen@updivision.com

**Comment by eugentudorache** [comment]
Hey,

Have you heard about that really wowsome stuff? You won't regret, believe me, read more here <http://quostyvevi.leggumms.com/aesogg>

Take care, eugen@updivision.com

**Comment by eugentudorache** [comment]
Hi,

It is so exciting to tell you about what happened yesterday, you should better read it yourself <http://rdoslumelte.debrisonthespeedway.com/aemqtdsf>

Cheers, eugen@updivision.com
