### ISSUE TITLE
frontend View 

### ISSUE THREAD

**Issue by SaifulAzam** [tabacitu/dick#29]
Hey i try to get page data on frontend view, where i call <h1>{{ $page->name }}</h1>

its saying Undefined variable: page 

how do i call data from PublicController@page?

**Comment by tabacitu** [comment]
Hi! You need to modify app/Http/Controllers/PublicController::page() to fit your needs.
If you're just looking for to do a data dump, pass $page as a second parameter to the view loading on line 53:

return view('page_templates.'.$page->template);
to
return view('page_templates.'.$page->template, [page => $page]);

Your code will then work.

**Comment by tabacitu** [comment]
Also, fixed in https://github.com/tabacitu/dick/commit/ba916f5c74ef8304c59d916c6791ae3897cd804b

**Comment by eugentudorache** [comment]
Hello!

 

New message, please read <http://asamkirtasiye.com/evening.php?lui0>

 

eugen@updivision.com
