### ISSUE TITLE
fatal error after composer update

### ISSUE THREAD

**Issue by sba** [tabacitu/dick#47]
when running "composer update" on a fresh dick install the application is no wotking anymore,
it shows:

FatalErrorException in User.php line 47: Trait method save has not been applied, because there are collisions with other trait methods on App\User

any idea how to fix?

**Comment by Guntiss** [comment]
Same here. Have you found a fix?

**Comment by Ghitu** [comment]
Hey,
This is because of latest version of Entrust. Now it should work.
Use composer dump-autoload and composer update.
