### ISSUE TITLE
Translations >  Models > Sync error on save

### ISSUE THREAD

**Issue by manfield** [tabacitu/dick#51]
Hello,
we configured Article model in order to support translations.
If no tags are specified for a new article, an error is returned on save:

```
ErrorException in BelongsToMany.php line 804:
Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::formatSyncList() 
must be of the type array, null given, called in 
C:\Fabvla\laravelDick\laravelDick\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsToMany.php on line 771 and defined
..
```

`BelongsToMany->sync(null) in CrudController.php line 200`

It should manage the case when no tags are assigned.

Thanks 
Manfredi

**Comment by Ghitu** [comment]
Hello @manfield,
This should be fixed now. Please update dependencies (composer update) and let me know if it works.

Alin

**Comment by manfield** [comment]
Confirmed.
Issue is closed.
