### ISSUE TITLE
Undefined index: fields at CrudController.php line 483 - After trying to reach Admin/Users Section.

### ISSUE THREAD

**Issue by dobromir-hristov** [tabacitu/dick#53]
Hi. Today I did two installations of the Admin panel package and both times I got this error when trying to check out the User section of the Admin panel.
Package looks lovely, going to check it out further. 
```
1. in CrudController.php line 483
2. at HandleExceptions->handleError('8', 'Undefined index: fields', 'C:\xampp\htdocs\dick_admin\vendor\dick\crud\src\Http\Controllers\CrudController.php', '483', array('fake_field_columns_to_encode' => array())) in CrudController.php line 483
```

**Comment by dobromir-hristov** [comment]
In UserCrudController.php if I add a fields array instead of created_fields and update_fields, error goes away.

**Comment by teamexpertois** [comment]
@dobromir-hristov: What is the change you did? Can you show me?

**Comment by dobromir-hristov** [comment]
that was a long time ago mate. And I think the mistake was with my way of installing not the package it self :) Just follow step by step their guide and you should be fine.
