### ISSUE TITLE
FatalErrorException in UserCrudController.php line 161 When Updating User.

### ISSUE THREAD

**Issue by dobromir-hristov** [tabacitu/dick#54]
```
FatalErrorException in UserCrudController.php line 161: Call to private method Dick\CRUD\Http\Controllers\CrudController::compactFakeFields() from context 'App\Http\Controllers\Admin\UserCrudController'
```
Edit:
Nvm... Did not update Composer....

**Comment by tabacitu** [comment]
May I just say that I love fact that you document the problems you've faced first installing Dick? And most of all, that you documented the fixes?

Thank you. A LOT!

v2 is coming this/next week, in the form of Laravel Backpack, your thoughts on it will be very appreciated.

Keep up the good work!

**Comment by dobromir-hristov** [comment]
Me and my team are really liking the project. We are constantly fixing and tinkering with it. I can contribute to the TODO fields if they are not finished in the V2 package. I added a couple of others that I found useful.

**Comment by tabacitu** [comment]
That sounds great! In backpack/crud the fields aren't very different, they are still separate files for each field type.

**Comment by dobromir-hristov** [comment]
Ok. Looking forward to the package :)
